services:
  circulars_db:
    image: postgres:16
    container_name: ia-vct-circular_db
    environment:
      POSTGRES_DB: circulars_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/miguel/circulars_db:/var/lib/postgresql/data
    networks:
      - srt_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 1

  srt:
    build:
      context: ../ia-vct-srt
      dockerfile: dockerfile
    container_name: ia-vct-srt
    environment:
      ON_CLOUD: 'True'
      TEST_MODE: 'False'
      PROMETHEUS_MULTIPROC_DIR: "/metrics/assetizer"
      SRT_PORT: "${SRT_PORT}"
      FFMPEG_ROOT: "${FFMPEG_ROOT}"
      LOGGING_LEVEL: 'INFO'
      LOGSTASH_PORT: "${LOGSTASH_PORT}"
      EXPOSE_LOGSTASH: "${EXPOSE_LOGSTASH}"
    volumes:
      - "${SRT_VOLUME}:/etc/configmaps"
      - "${SRT_SECRETS}:/etc/secrets"
      - "${GLOBAL_VOLUME}:/workspace_downloader"
      - "${SRT_LOGS}:/var/log/srt"
      - "${SRT_METRICS}:/metrics"
    restart: "no"
    ports:
      - "9060:9060"
    networks:
      - srt_network
    depends_on:
      circulars_db:
        condition: service_healthy

  adminer: # Service that allows to check the db
    image: adminer
    networks:
      - srt_network
    restart: always
    ports:
      - 8080:8080

networks:
  srt_network:
    external: true
    name: srt_network
    driver: bridge

volumes:
  pgdata: