services:

  controller_db_server:
    build:
      context: ../ia-vct-controller_db_server
      dockerfile: Dockerfile
    ports:
      - "${CONTROLLER_DB_SERVER_PORT}:8035"
    command: gunicorn -w 1 -b 0.0.0.0:8035 --timeout 3600 app:app
    environment:
      ON_CLOUD: "True"
      CONTROLLER_DB_SERVER_PORT: "${CONTROLLER_DB_SERVER_PORT}"
      CONTROLLER_DB_SERVER_LOGS: "${CONTROLLER_DB_SERVER_LOGS}"
      LOGGING_LEVEL: "${LOGGING_LEVEL}"
      LOGSTASH_PORT: "${LOGSTASH_PORT}"
      EXPOSE_LOGSTASH: "${EXPOSE_LOGSTASH}"
    networks:
      - epg_network
    volumes:
      - "${CONTROLLER_DB_SERVER_VOLUME}:/etc/configmaps"
      - "${CONTROLLER_DB_SECRETS_ROOT}:/etc/secrets"
      - "${CONTROLLER_DB_SERVER_LOGS}:/var/log/controller_db_server"
    depends_on:
      - controller_db

  controller_db:
    build:
      context: ../ia-vct-controller_db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: controller_db
    networks:
      - epg_network
    # network_mode: host
    volumes:
      - "${CONTROLLER_DB_ROOT}:/var/lib/postgresql/data"

  assetizer:
    build:
      context: ../ia-vct-assetizer
      dockerfile: Dockerfile
    ports:
      - "${ASSETIZER_PORT}:8050"
    command: gunicorn -w 1 -b 0.0.0.0:8050 --timeout 3600 app:app
    environment:
      ON_CLOUD: 'True'
      TEST_MODE: 'False'
      PROMETHEUS_MULTIPROC_DIR: "/metrics/assetizer"
      ASSETIZER_PORT: "${ASSETIZER_PORT}"
      ASSETIZER_VOLUME: "${ASSETIZER_VOLUME}"
      ASSETIZER_LOGS: "${ASSETIZER_LOGS}"
      FFMPEG_ROOT: "${FFMPEG_ROOT}"
      LOGGING_LEVEL: "${LOGGING_LEVEL}"
      LOGSTASH_PORT: "${LOGSTASH_PORT}"
      EXPOSE_LOGSTASH: "${EXPOSE_LOGSTASH}"
    networks:
      - epg_network
    volumes:
      - "${ASSETIZER_VOLUME}:/etc/configmaps"
      - "${GLOBAL_VOLUME}:/workspace_downloader"
      - "${ASSETIZER_LOGS}:/var/log/assetizer"
      - "${ASSETIZER_METRICS}:/metrics"

  transcript:
    build:
      context: ../ia-vct-transcript
      dockerfile: Dockerfile
    ports:
      - "${TRANSCRIPT_PORT}:8028"
    command: gunicorn -w 2 -b 0.0.0.0:8028 --timeout 3600 app:app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      ON_CLOUD: "True"
      TRANSCRIPT_PORT: "${TRANSCRIPT_PORT}"
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
      LOGGING_LEVEL: "${LOGGING_LEVEL}"
      LOGSTASH_PORT: "${LOGSTASH_PORT}"
      EXPOSE_LOGSTASH: "${EXPOSE_LOGSTASH}"
    runtime: nvidia
    networks:
      - epg_network
    # network_mode: host
    volumes:
      - "${TRANSCRIPT_VOLUME}:/etc/configmaps"
      - "${GLOBAL_VOLUME}:/workspace_downloader"
      - "${TRANSCRIPT_LOGS}:/var/log/transcript"

  recorder:
    build:
      context: ../ia-vct-recorder
      dockerfile: Dockerfile
    ports:
      - "${RECORDER_PORT}:8060"
    command: gunicorn -w 1 -b 0.0.0.0:8060 --timeout 3600 app:app
    environment:
      ON_CLOUD: 'True'
      TEST_MODE: 'False'
      RECORDER_PORT: "${RECORDER_PORT}"
      RECORDER_VOLUME: "${RECORDER_VOLUME}"
      RECORDER_LOGS: "${RECORDER_LOGS}"
      PROMETHEUS_MULTIPROC_DIR: '/metrics/recorder'
      FFMPEG_ROOT: "${FFMPEG_ROOT}"
      LOGGING_LEVEL: "${LOGGING_LEVEL}"
      LOGSTASH_PORT: "${LOGSTASH_PORT}"
      EXPOSE_LOGSTASH: "${EXPOSE_LOGSTASH}"
    networks:
      - epg_network
    volumes:
      - "${RECORDER_VOLUME}:/etc/configmaps"
      - "${GLOBAL_VOLUME}:/workspace_downloader"
      - "${RECORDER_METRICS}:/metrics"
      - "${RECORDER_LOGS}:/var/log/recorder:rw"

  srt-caller-la1:
    build:
      context: ../ia-vct-srt_gstreamer
      dockerfile: dockerfile
   #  env_file: .env   # contains SRT_HOST, common knobs
    environment:
      ID3_HZ: 2.0
      CHANNEL: "La1.es"
      SRT_HOST: "ia-vct-srt"
      SRT_PORT: 1231
      MP4_PATH: "/media/La1.es_20250922_155000.mp4"
      # MP4_PATH: "/media/B.mp4"
      # MP4_PATH: "/media/C.mp4"
    volumes:
      - /home/miguel/temp/La1.es_20250922_155000.mp4:/media/La1.es_20250922_155000.mp4:ro
      # - /home/miguel/temp/B.mp4:/media/B.mp4:ro
      #  - /home/miguel/temp/C.mp4:/media/C.mp4:ro
    networks: [epg_network]
    depends_on:
      - srt

  circulars_db:
    image: postgres:16
    container_name: ia-vct-circular_db
    environment:
      POSTGRES_DB: circulars_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/miguel/circulars_db:/var/lib/postgresql/data
    networks:
      - epg_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 1

  srt:
    build:
      context: ../ia-vct-srt
      dockerfile: dockerfile
    container_name: ia-vct-srt
    environment:
      ON_CLOUD: 'True'
      TEST_MODE: 'False'
      PROMETHEUS_MULTIPROC_DIR: "/metrics/assetizer"
      SRT_PORT: "${SRT_PORT}"
      FFMPEG_ROOT: "${FFMPEG_ROOT}"
      LOGGING_LEVEL: 'INFO'
      LOGSTASH_PORT: "${LOGSTASH_PORT}"
      EXPOSE_LOGSTASH: "${EXPOSE_LOGSTASH}"
    volumes:
      - "${SRT_VOLUME}:/etc/configmaps"
      - "${SRT_SECRETS}:/etc/secrets"
      - "${GLOBAL_VOLUME}:/workspace_downloader"
      - "${SRT_LOGS}:/var/log/srt"
      - "${SRT_METRICS}:/metrics"
    restart: "no"
    ports:
      - "${SRT_PORT}:9060"
    networks:
      - epg_network
    depends_on:
      circulars_db:
        condition: service_healthy

  adminer: # Service that allows to check the db
    image: adminer
    # network_mode: host
    networks:
      - epg_network
    restart: always
    ports:
      - 8080:8080

  ocr:
    build:
      context: ../ia-vct-ocr
      dockerfile: Dockerfile
    container_name: ocr
    environment:
        TEST_MODE: 'False'
        ON_CLOUD: 'True'
        FLASK_HOST: "${OCR_HOST}"
        # FLASK_PORT: "${OCR_PORT}"
        AZURE_VISION_KEY:  "${OCR_AZURE_VISION_KEY}"
        AZURE_VISION_ENDOINT: "${OCR_AZURE_VISION_ENDPOINT}"
        API_REVERSE_PROXY: "${OCR_API_REVERSE_PROXY}"
        NVIDIA_VISIBLE_DEVICES: 0
        LOGGING_LEVEL: "${LOGGING_LEVEL}"
        LOGSTASH_PORT: "${LOGSTASH_PORT}"
        EXPOSE_LOGSTASH: "${EXPOSE_LOGSTASH}"
    ports:
      - "${OCR_PORT}:7007"
    volumes:
      - "${GLOBAL_VOLUME}:/workspace_downloader"
      - "${OCR_VOLUME}:/etc/configmaps:ro"
    # command: ["gunicorn", "-w", "1", "-k", "gthread", "--threads", "2", "-b", "0.0.0.0:7007", "app:app"]
    command: python3 app.py
    runtime: nvidia
    networks:
      - epg_network

  sbd:
    build:
      context: ../ia-vct-sbd
      dockerfile: Dockerfile
    container_name: sbd
    environment:
      TEST_MODE: 'False'
      ON_CLOUD: 'True'
      FLASK_HOST: "${SBD_HOST}"
      # FLASK_PORT: "${SBD_PORT}"
      API_REVERSE_PROXY: "${SBD_API_REVERSE_PROXY}"
      LOGGING_LEVEL: "${LOGGING_LEVEL}"
      LOGSTASH_PORT: "${LOGSTASH_PORT}"
      EXPOSE_LOGSTASH: "${EXPOSE_LOGSTASH}"
    ports:
      - "${SBD_PORT}:9009"
    volumes:
      - "${GLOBAL_VOLUME}:/workspace_downloader"
      - "${SBD_VOLUME}:/etc/configmaps:ro"
    command: ["gunicorn", "-w", "1", "-k", "gthread", "--threads", "2", "-b", "0.0.0.0:9009", "app:app"]
    networks:
      - epg_network


networks:
  epg_network:
    driver: bridge
