services:
  srt-caller-la1:
    build:
      context: ../ia-vct-srt_gstreamer
      dockerfile: Dockerfile
    environment:
      ID3_HZ: 2.0
      CHANNEL: "La1.es"
      SRT_HOST: "ia-vct-srt"
      SRT_PORT: 1231
      # MP4_PATH: "/media/La1.es_20250922_155000.mp4"
      MP4_PATH: "/media/B.mp4"
      # MP4_PATH: "/media/C.mp4"
    volumes:
      # - /home/miguel/temp/La1.es_20250922_155000.mp4:/media/La1.es_20250922_155000.mp4:ro
      - /home/miguel/temp/B.mp4:/media/B.mp4:ro
      #  - /home/miguel/temp/C.mp4:/media/C.mp4:ro
    networks: [srt_network]
   #  network_mode: host


networks:
  srt_network:
    external: true
    name: srt_network
    driver: bridge