input {
  udp {
    port => 5000
    codec => json  # Procesa los logs como JSON
  }
}

filter {

  # Filtrar por nivel de log (DEBUG, INFO, WARNING, ERROR, CRITICAL, SUMMARY)
  if [log_level] == "DEBUG" {
    mutate { add_field => { "log_type" => "debug" } }
  } else if [log_level] == "INFO" {
    mutate { add_field => { "log_type" => "info" } }
  } else if [log_level] == "WARNING" {
    mutate { add_field => { "log_type" => "warning" } }
  } else if [log_level] == "ERROR" {
    mutate { add_field => { "log_type" => "error" } }
  } else if [log_level] == "CRITICAL" {
    mutate { add_field => { "log_type" => "critical" } }
  } else if [log_level] == "SUMMARY" {
    mutate { add_field => { "log_type" => "summary" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "server_logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}